language: python
python:
  - "2.7"
services:
  - elasticsearch
install:
  - pip install flake8
  - python setup.py install
script:
  # FIXME: Test all
  - python manage.py test admin --settings=pursuite.settings.testing
  - flake8 .
